### ISSUE TITLE
Unstable/unusable build scripts

### ISSUE THREAD

**Issue by JagannathS** [uw-ictd/colte#24]
Hi when trying to build from source using ./system_setup/install.sh source_build 

also we would want to do a full build of the system with all the features mentioned in the wordpress blog. Please let us know a way to so it.

Getting the following error
TASK [build_epc : create .deb files] *********************************************************************************************************
task path: /home/colte/Downloads/colte/system_setup/roles/build_epc/tasks/main.yml:121
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/colte/.ansible/tmp/ansible-tmp-1544458667.8-159391804769370 `" && echo ansible-tmp-1544458667.8-159391804769370="` echo /home/colte/.ansible/tmp/ansible-tmp-1544458667.8-159391804769370 `" ) && sleep 0'
<localhost> PUT /home/colte/.ansible/tmp/ansible-local-48354i8CqJJ/tmplgWxzK TO /home/colte/.ansible/tmp/ansible-tmp-1544458667.8-159391804769370/command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/colte/.ansible/tmp/ansible-tmp-1544458667.8-159391804769370/ /home/colte/.ansible/tmp/ansible-tmp-1544458667.8-159391804769370/command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/colte/.ansible/tmp/ansible-tmp-1544458667.8-159391804769370/command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/colte/.ansible/tmp/ansible-tmp-1544458667.8-159391804769370/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": "dpkg-deb --build db colte-db_0.9.5bionic_amd64.deb\n dpkg-deb --build hss colte-hss_0.9.6bionic_amd64.deb\n dpkg-deb --build mme colte-mme_0.9.3bionic_amd64.deb\n dpkg-deb --build spgw colte-spgw_0.9.7bionic_amd64.deb\n dpkg-deb --build colteconf colte-conf_0.9.5bionic_amd64.deb\n dpkg-deb --build epc colte-epc_0.9.5bionic_amd64.deb", 
    "delta": "0:00:00.607558", 
    "end": "2018-12-10 21:47:48.567491", 
    "invocation": {
        "module_args": {
            "_raw_params": "dpkg-deb --build db colte-db_0.9.5bionic_amd64.deb\n dpkg-deb --build hss colte-hss_0.9.6bionic_amd64.deb\n dpkg-deb --build mme colte-mme_0.9.3bionic_amd64.deb\n dpkg-deb --build spgw colte-spgw_0.9.7bionic_amd64.deb\n dpkg-deb --build colteconf colte-conf_0.9.5bionic_amd64.deb\n dpkg-deb --build epc colte-epc_0.9.5bionic_amd64.deb", 
            "_uses_shell": true, 
            "chdir": "/home/colte/Downloads/colte/package", 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 2, 
    "start": "2018-12-10 21:47:47.959933", 
    "stderr": "dpkg-deb: error: failed to open package info file 'db/DEBIAN/control' for reading: No such file or directory\ndpkg-deb: error: failed to open package info file 'hss/DEBIAN/control' for reading: No such file or directory\ndpkg-deb: error: failed to open package info file 'mme/DEBIAN/control' for reading: No such file or directory\ndpkg-deb: error: failed to open package info file 'spgw/DEBIAN/control' for reading: No such file or directory\ndpkg-deb: error: failed to open package info file 'colteconf/DEBIAN/control' for reading: No such file or directory\ndpkg-deb: error: failed to open package info file 'epc/DEBIAN/control' for reading: No such file or directory", 
    "stderr_lines": [
        "dpkg-deb: error: failed to open package info file 'db/DEBIAN/control' for reading: No such file or directory", 
        "dpkg-deb: error: failed to open package info file 'hss/DEBIAN/control' for reading: No such file or directory", 
        "dpkg-deb: error: failed to open package info file 'mme/DEBIAN/control' for reading: No such file or directory", 
        "dpkg-deb: error: failed to open package info file 'spgw/DEBIAN/control' for reading: No such file or directory", 
        "dpkg-deb: error: failed to open package info file 'colteconf/DEBIAN/control' for reading: No such file or directory", 
        "dpkg-deb: error: failed to open package info file 'epc/DEBIAN/control' for reading: No such file or directory"
    ], 
    "stdout": "", 
    "stdout_lines": []
}
	to retry, use: --limit @/home/colte/Downloads/colte/system_setup/source_build.retry

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=12   changed=4    unreachable=0    failed=1 

Regards,
Jagannath

**Comment by spencersevilla** [comment]
Standby; I am 90% done with rewriting some Makefiles, will push and update within the week.

**Comment by spencersevilla** [comment]
Closed by 7f17e34, which refactors the codebase and pushes EPC code into https://github.com/uw-ictd/openair-cn.git
