### ISSUE TITLE
webadmin: simple status monitor page

### ISSUE THREAD

**Issue by spencersevilla** [uw-ictd/colte#34]
I want a "status" tab that displays the following information:

- systemctl status (active/dead, enabled/disabled, how long running, etc.) for the following services:
colte-hss, colte-mme, colte-spgw, haulage, colte-webgui. use the command "systemctl status" to request information.Note that haulage may-or-may not be installed on the system, so be sure to handle it in some form (e.g. "haulage not installed"). This error-handling doesn't have to be particularly pretty because we'll eventually re-architect and separate haulage/user management out from this tab.

- general system health (cpu, memory, disk). We can get this information by querying "/proc".

**Comment by matt9j** [comment]
OBE not implemented.
