### ISSUE TITLE
webadmin not installed by default

### ISSUE THREAD

**Issue by kheimerl** [uw-ictd/colte#42]
Webadmin doesn't seem installed; there's no systemd file (unlike for the webgui, which is there and works)

**Comment by kheimerl** [comment]
Oh it's a separate package that needs to be installed. I'll update the documentation but maybe add it to the metapackage?

**Comment by spencersevilla** [comment]
The main reason why this is the case is that the table-pagination library in the webadmin needs nodejs version 8 and Debian 9 currently ships with nodejs 4. Once Debian 10 lands (June, I believe) this will be a moot problem and I will add to metapackage. Note that this problem does not apply to Ubuntu 18.04.
