### ISSUE TITLE
webgui needs to touch /var/log/colte/transaction_log.txt

### ISSUE THREAD

**Issue by spencersevilla** [uw-ictd/colte#49]
If this file (or more specifically, the /var/log/colte directory) does not exist, webgui will fail and not start up.

**Comment by infrared0** [comment]
Is this bug fixed?

**Comment by spencersevilla** [comment]
fairly certain it is. used to be separate packages (colte vs colte-webgui vs colte-webadmin) but now we've condensed them into one.
