### ISSUE TITLE
npm installs are erroring out with "UNMET PEER DEPENDENCY"

### ISSUE THREAD

**Issue by spencersevilla** [uw-ictd/colte#64]
I believe this is caused by bit-rot due to Ubuntu upgrading to a newer version of npm, think the fix is to improve our package.json file. Not yet sure if this is just a warning we can ignore, or impacts the build itself.

Refs:
https://stackoverflow.com/questions/36186567/what-does-unmet-peer-dependency-packagename-extraneous-mean/39775086
https://stackoverflow.com/questions/35738346/how-do-i-fix-the-npm-unmet-peer-dependency-warning

**Comment by matt9j** [comment]
I updated package.json in the admin and webfui on master to address some security warnings, but tested locally and had no issues. The problem could be related to that? How can I help debug?

**Comment by spencersevilla** [comment]
I doubt you caused this. Digging into the errors, it looks like knex has specified dependencies, npm is not automatically fetching them, but then complaining.

Me and @jliang9 have been having some work-parties this week to just fix all the bit-rot and migrate colte over to an open5gs base (see branch migrate_open5gs). This bug is more a reminder so we don't forget, but will be addressed tomorrow.

**Comment by matt9j** [comment]
This should be resolved now!
