### ISSUE TITLE
Right way to update COLTE

### ISSUE THREAD

**Issue by rembulan** [uw-ictd/colte#79]
Could someone give me direction the right way to update COLTE when a new update appear

**Comment by matt9j** [comment]
Hi Rembulan,
The right way to update will depend on how you installed the software originally. If you installed via the recommended apt packages route, we will tag a release and publish an update once we complete our internal tests for stability (currently ongoing). If you installed directly from source, it will depend on your specific system and the details of your install. Let me know if you need more help than that! I can update you here when the new release goes out (likely early next week).

**Comment by matt9j** [comment]
Hi @rembulan, thanks for your patience with the delay. New packages have been created, tested, and pushed to the repository, so you should be able to upgrade now with the regular apt workflow of `apt-get update` followed by `apt-get upgrade`.

**Comment by matt9j** [comment]
I'm going to close this for now-- please reach out if you have any issues!
